更换哔哩哔哩直播使用的api，添加直播间标题修改时推送直播间的功能
felinae98/nonebot-bison pull request #128
Opened 2022-10-17 06:53 UTC by AzideCupric

2022-10-17 10:30 UTC, felinae98 commented
推荐不要使用全局配置来控制是否对比直播间标题，可以通过订阅不同的 categories 来控制这个行为

2022-10-17 10:50 UTC, AzideCupric commented
> 推荐不要使用全局配置来控制是否对比直播间标题，可以通过订阅不同的 categories 来控制这个行为

主要是想偷懒来着(

2022-10-18 04:47 UTC, felinae98 requested changes

2022-10-18 04:47 UTC, felinae98 commented on src/plugins/nonebot_bison/platform/bilibili.py
> +        if self.is_live_turn_on(old_status["live_status"], new_status["live_status"]):
不要直接对 old_status 和 new_status 进行修改，如果要修改和返回请先进行 deep copy

2022-10-18 04:47 UTC, felinae98 commented on src/plugins/nonebot_bison/platform/bilibili.py
>              info = {}
info 建议写成一个 pydantic 的 dataclasss

2022-10-18 16:02 UTC, AzideCupric commented on src/plugins/nonebot_bison/platform/bilibili.py
>              info = {}
直接把dict丢给__init__初始化应该没问题的吧

2022-10-19 12:28 UTC, felinae98 requested changes

2022-10-19 12:28 UTC, felinae98 commented on src/plugins/nonebot_bison/platform/bilibili.py
> +        def __and__(self, old_info: Self) -> bool:
不建议重载 & 和 ^ 运算符，可以封装成函数，也可以直接把逻辑放在 compare_status 里。这样代码看起来很容易让人迷惑

2022-10-19 12:33 UTC, AzideCupric commented on src/plugins/nonebot_bison/platform/bilibili.py
> +        def __and__(self, old_info: Self) -> bool:
看起来比较整洁而且也有相应的注释了，所以我觉得没问题(主要是好玩
本来是写成函数形式的，我觉得太长了不好看就改掉了(还不用考虑命名问题

2022-10-19 15:48 UTC, felinae98 approved these changes
LGTM

2022-10-19 15:49 UTC, merged