小刻食堂主题分享卡片
felinae98/nonebot-bison pull request #304
Opened 2023-07-25 15:44 UTC by phidiaLam

2023-07-25 16:00 UTC, AzideCupric requested changes

2023-07-25 16:04 UTC, AzideCupric requested changes

2023-07-25 16:04 UTC, AzideCupric commented on nonebot_bison/post/cards/themes/bison/templates/ceobecanteen.html.jinja
> +                    <div class="linkage">bison&小刻食堂联动</div>
```suggestion
                    <div class="linkage">bison&amp;小刻食堂联动</div>
```

2023-07-25 16:04 UTC, AzideCupric commented on nonebot_bison/post/cards/themes/bison/templates/ceobecanteen.html.jinja
> +                <img class='ceobe-logo' src="{{ card.info.ceobecanteen_logo }}">
logo作为一个几乎不会变动的图片，直接写死路径就好了吧

2023-07-25 16:04 UTC, AzideCupric commented on nonebot_bison/post/cards/themes/bison/templates/ceobecanteen.html.jinja
> +                <img class='bison-logo' src="{{ card.info.bison_logo }}">
bison的logo也是

2023-07-25 16:05 UTC, phidiaLam commented on nonebot_bison/post/cards/themes/bison/templates/ceobecanteen.html.jinja
> +                <img class='bison-logo' src="{{ card.info.bison_logo }}">
主要不知道放哪里

2023-07-27 15:40 UTC, AzideCupric approved these changes

2023-07-28 17:01 UTC, merged